---
# handlers file for firewall

- name: Reload firewall
  ansible.builtin.service:
    name: "{{ firewall_service }}"
    state: reloaded
  when:
    - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
    - not ansible_check_mode

- name: Reload firewalld
  ansible.builtin.command:
    cmd: firewall-cmd --reload

- name: restart NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: restarted
  when:
    - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
    - not ansible_check_mode | bool
