Vagrant.configure("2") do |config|
    config.vm.define "alma8" do |alma8|
      alma8.vm.box = "generic/alma8"
    end
    config.vm.define "centos7" do |centos7|
      centos7.vm.box = "generic/centos7"
    end
    config.vm.define "centos8" do |centos8|
      centos8.vm.box = "generic/centos8"
    end
    # config.vm.define "fedora28" do |fedora28|
    #   fedora28.vm.box = "generic/fedora28"
    # end
    # config.vm.define "fedora29" do |fedora29|
    #   fedora29.vm.box = "generic/fedora29"
    # end
    config.vm.define "fedora35" do |fedora35|
      fedora35.vm.box = "generic/fedora35"
    end
    config.vm.define "opensuse15" do |opensuse15|
      opensuse15.vm.box = "generic/opensuse15"
    end
    config.vm.define "rhel7" do |rhel7|
      rhel7.vm.box = "generic/rhel7"
    end
    config.vm.define "rhel8" do |rhel8|
      rhel8.vm.box = "generic/rhel8"
    end
  end